### ISSUE TITLE
原理一说就懂，看完Readme有点想卸载windows chrome

### ISSUE THREAD

**Issue by AM-young-fun** [justjavac/steal_password_from_browser#33]

**Comment by justjavac** [comment]
卸载完装什么呢？

**Comment by AM-young-fun** [comment]
Tor 【

**Comment by justjavac** [comment]
只要不保存密码就行了

**Comment by WangNianyi2001** [comment]
Firefox 有这个漏洞莫

**Comment by justjavac** [comment]
> Firefox 有这个漏洞莫

应该也有，本质上是 Windows 系统的问题。Windows 的这 2 个加密解密 api 只能保证“如果黑客偷走了你的密码文件，无法在其它电脑上解密”。但是如果遇到流氓软件，可以在你的电脑上获得密码。

**Comment by WangNianyi2001** [comment]
> 应该也有，本质上是 Windows 系统的问题。Windows 的这 2 个加密解密 api 只能保证“如果黑客偷走了你的密码文件，无法在其它电脑上解密”。但是如果遇到流氓软件，可以在你的电脑上获得密码。

那理论上来说是不是可以搞个特洛伊直接往恶意服务器发明文（嘶）

**Comment by justjavac** [comment]
> > 应该也有，本质上是 Windows 系统的问题。Windows 的这 2 个加密解密 api 只能保证“如果黑客偷走了你的密码文件，无法在其它电脑上解密”。但是如果遇到流氓软件，可以在你的电脑上获得密码。
> 
> 那理论上来说是不是可以搞个特洛伊直接往恶意服务器发明文（嘶）

是的
